# Generated by Django 3.0.4 on 2020-11-14 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_dynamic_password_validator'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='validators',
            field=models.ManyToManyField(blank=True, to='core.DynamicPasswordValidator'),
        ),
    ]
